apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtaptestlzhuang/test-go:5832152011d9c03a51ebeae12df2538c466de21b@sha256:35bd0d060f5bd8bff2862905b5018fbb52bfda6c255024cbbd658cb718ffa46e
          name: container-image
